version: "3.8"
services:
  app:
    container_name: "queue-demo-server"
    build:
      context: .
      dockerfile: Dockerfile
    image: queue-demo-server:latest
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    command: >
      bash -c "composer install && php artisan serve --host=0.0.0.0 --port=8000"
    networks:
      - queue-demo-network
    depends_on:
      - mysql
  mysql:
    container_name: "queue-demo-database"
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: queue-demo
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: "%"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - queue-demo-network
volumes:
  mysql_data:
    driver: local
networks:
  queue-demo-network:
    driver: bridge
